### ISSUE TITLE
Use case using BitWarden to secure customer-supplier process

### ISSUE THREAD

**Issue by Tlathrop01** [PatrickBN/CYBR8420_Team5#6]
This is Debaris's use case.

**Comment by Dezuma** [comment]
Attaching Use case example: [Customer-Supplier](https://app.diagrams.net/#G1jnoGJhqMim_AxAHLtqiIRVLqeKS2eG7J#%7B%22pageId%22%3A%22C5RBs43oDa-KdzZeNtuy%22%7D)
